const test=require('node:test'),assert=require('node:assert/strict'),M=require('../js/modules/character-sheet-model'),C=require('../js/modules/character-catalog'),A=require('../js/modules/character-actions'),S=require('../js/modules/character-story');
C.set(require('../data/rules/catalog.json'));
const base=()=>M.normalize({build:{edition:'2024',classId:'fighter',scoreMode:'base'},abilities:{str:18,dex:14,int:16,con:14}});
const run=(a,data=base(),level=5,loot=[])=>{data.actions=[a];return M.derive(data,level,loot).actions[0];};
test('Battleaxe automatically uses Strength and versatile damage',()=>{const one=run({kind:'weapon',ref:'battleaxe'}),two=run({kind:'weapon',ref:'battleaxe',mode:'twoHanded'});assert.equal(one.hit,'+7');assert.equal(one.damage,'1d8 + 4 slashing');assert.equal(two.damage,'1d10 + 4 slashing');});
test('Finesse thrown dagger uses the better ability; thrown handaxe uses STR',()=>{const d=base();d.abilities.dex=20;assert.equal(run({kind:'weapon',ref:'dagger',mode:'thrown'},d).damage,'1d4 + 5 piercing');assert.equal(run({kind:'weapon',ref:'handaxe',mode:'thrown'},d).damage,'1d6 + 4 slashing');assert.equal(run({kind:'weapon',ref:'dagger',mode:'thrown'},d).range,'20/60');});
test('Changing an ability recalculates the same saved action',()=>{const d=base(),action={kind:'weapon',ref:'battleaxe'};assert.equal(run(action,d).hit,'+7');d.abilities.str=12;assert.equal(run(action,d).hit,'+4');assert.equal(run(action,d).damage,'1d8 + 1 slashing');});
test('Linked loot uses current magical bonuses and stops when ownership ends',()=>{const d=base(),action={kind:'loot',ref:'owned'},loot=[{id:'owned',quantity:1,item:{name:'Battleaxe +1'}}];assert.equal(run(action,d,5,loot).damage,'1d8 + 5 slashing');loot[0].item.name='Battleaxe +2';assert.equal(run(action,d,5,loot).hit,'+9');loot[0].quantity=0;assert.equal(run(action,d,5,loot).available,false);});
test('2024 net is a DEX saving throw with no damage; 2014 net uses an attack',()=>{const d=base();assert.equal(run({kind:'weapon',ref:'net'},d).hit,'DEX DC 13');assert.equal(run({kind:'weapon',ref:'net'},d).ability,'dex');assert.equal(run({kind:'weapon',ref:'net'},d).damage,'Restrained; no damage');d.build.edition='2014';assert.equal(run({kind:'weapon',ref:'net'},d).hit,'+5');});
test('Improvised attacks omit proficiency unless a feature grants it',()=>{assert.equal(run({kind:'improvised'}).hit,'+4');assert.equal(run({kind:'improvised',mode:'thrown'}).hit,'+2');assert.equal(run({kind:'improvised'}).damage,'1d4 + 4 (DM chooses type)');});
function spell(name,edition='2024',slot=0,level=5){const d=base(),s=C.data.spells.find(s=>s.name===name&&s.edition===edition);d.spellAbility='int';d.spells=[C.spellRow(s)];return run({kind:'spell',ref:s.id,slot},d,level);}
test('Fire Bolt uses INT to hit, level-scaled dice, and no INT damage bonus',()=>{assert.equal(spell('Fire Bolt').hit,'+6');assert.equal(spell('Fire Bolt').damage,'2d10 fire');assert.equal(spell('Fire Bolt','2024',0,17).damage,'4d10 fire');});
test('Fireball calculates save DC and higher-slot damage instead of an attack roll',()=>{assert.equal(spell('Fireball','2024',5).hit,'DEXTERITY DC 14');assert.equal(spell('Fireball','2024',5).damage,'10d6 fire');});
test('Multi-ray and dart spells distinguish per-hit damage from attack count',()=>{assert.equal(spell('Eldritch Blast').damage,'1d10 force per beam × 2');assert.equal(spell('Scorching Ray','2024',4).damage,'2d6 fire per ray × 5');assert.equal(spell('Magic Missile','2024',3).damage,'1d4 + 1 force per dart × 5');assert.equal(spell('Magic Missile').hit,'Effect');});
test('Spiritual Weapon alone adds casting modifier and respects edition upcasting',()=>{assert.equal(spell('Spiritual Weapon','2024',3).damage,'2d8 + 3 force');assert.equal(spell('Spiritual Weapon','2014',3).damage,'1d8 + 3 force');});
test('Dragonborn breath derives CON DC, ancestry damage and edition scaling',()=>{const d=base();d.build.race='dragonborn-2024';d.build.dragon='red';const a=run({kind:'racial',ref:'breath'},d);assert.equal(a.hit,'DEX DC 13');assert.equal(a.damage,'2d10 Fire');d.build.race='human-2024';assert.equal(run({kind:'racial',ref:'breath'},d).available,false);});
test('Weapon-dependent spell does not invent an unsupported damage formula',()=>{assert.equal(spell('True Strike').damage,'See spell effect');});
test('Action normalization preserves choices, bounds slots and limits count',()=>{const a=A.normalize([{kind:'weapon',ref:'battleaxe',mode:'twoHanded',slot:99}]);assert.deepEqual(A.normalize(a),a);assert.equal(a[0].slot,9);assert.equal(A.normalize(Array(70).fill({})).length,60);});
test('Background suggestions follow edition-neutral background identity and variants',()=>{assert.deepEqual(S.get('criminal-2014'),S.get('criminal-2024'));assert.deepEqual(S.get('spy-2014'),S.get('criminal-2014'));assert.notDeepEqual(S.get('criminal-2024'),S.get('noble-2024'));assert.equal(S.get('custom').personality.length,0);});
