(async()=>{
 const results=[];const check=(name,ok)=>{results.push({name,pass:!!ok});if(!ok)throw Error(name);};
 const tick=()=>new Promise(r=>setTimeout(r,10));const click=async selector=>{const b=document.querySelector(selector);if(!b)throw Error('Missing control '+selector);b.click();await tick();};
 try{
 seed('dm');
 check('DM sees campaign character inventory quantities',document.querySelector('[data-dm-loot="c1"]').textContent==='Looted (2)'&&document.querySelector('[data-dm-loot="c2"]').textContent==='Looted (3)');
 check('DM gets campaign item editor, not root editor',document.querySelector('#card-container .edit-button').textContent==='Edit Campaign Item');
 await click('[data-dm-loot="c1"]');
 check('DM character popup shows full item cards with quantity',document.querySelector('#characterLootCards .item-description').textContent==='Full potion description'&&document.querySelector('#characterLootCards .inventory-quantity').textContent==='Owned: 2');
 check('DM popup has unloot and transfer controls',!!document.querySelector('#characterLootCards .unloot-button')&&!!document.querySelector('#characterLootCards .transfer-button'));
 await click('#characterLootCards .unloot-button');
 check('Unloot opens quantity dialog',document.getElementById('vaultActionDialog').open&&document.querySelector('#actionQuantity').value==='1');
 await click('#confirmInventoryAction');
 check('Unloot runs inventory operation and refreshes owned quantity',callLog.at(-1).name==='vaultInventoryAction'&&callLog.at(-1).data.action==='unloot'&&document.querySelector('#characterLootCards .inventory-quantity').textContent==='Owned: 1');
 closeCharacterLoot();
 openItemModal(items[0]);
 check('Campaign field is readonly and matches current campaign',document.getElementById('modal-campaign').readOnly&&document.getElementById('modal-campaign').value==='Storm Coast');
 check('DM editor includes supply and looting mode',!!document.getElementById('modal-remaining')&&!!document.getElementById('modal-unlimited')&&!!document.getElementById('modal-lootMode'));
 document.getElementById('modal-campaign').value='Tampered name';document.getElementById('modal-name').value='DM Potion';await click('#saveItemModal');
 check('Save request excludes editable campaign text and includes campaign ID',callLog.at(-1).data.campaignId==='a'&&!('campaign' in callLog.at(-1).data.item)&&callLog.at(-1).data.stockRevision===8);
 check('Campaign save does not change root catalogue',rootItems[0].name==='Root Healing Potion');
 activeCampaign.name='New Campaign Name';openItemModal(items[0]);
 check('Renamed campaign appears automatically in locked editor',document.getElementById('modal-campaign').value==='New Campaign Name');closeItemModal();renderCards();
 check('Renamed campaign appears automatically on item cards',document.querySelector('#card-container .campaign-tag').textContent.includes('New Campaign Name'));
 await click('#card-container .clone-button');
 check('Clone calls campaign-scoped operation',callLog.at(-1).name==='vaultCopyCampaignItem'&&callLog.at(-1).data.source==='campaign'&&callLog.at(-1).data.campaignId==='a');
 check('Cloned item editor keeps campaign name locked',document.getElementById('modal-campaign').readOnly&&document.getElementById('modal-campaign').value==='New Campaign Name');closeItemModal();
 openItemModal();check('New item defaults to hidden, one copy, DM assignment',!document.getElementById('modal-visible').checked&&document.getElementById('modal-remaining').value==='1'&&document.getElementById('modal-lootMode').value==='dm');closeItemModal();
 await openRootPicker();await click('[data-root-id="root-potion"]');
 check('Root picker creates a campaign copy',callLog.at(-1).data.source==='root'&&callLog.at(-1).data.campaignId==='a');closeItemModal();
 seed('player');
 check('Player sees visible campaign items only',document.querySelectorAll('#card-container .item-card').length===2&&!document.querySelector('#card-container [data-item-id="hidden"]'));
 check('Player sees only own loot quantity, no other character names',document.querySelector('#card-container [data-item-id="potion"] .inventory-quantity').textContent==='You own: 2'&&!document.getElementById('card-container').textContent.includes('Elara'));
 check('Player card has no stock count or editing controls',!document.querySelector('#card-container .edit-button')&&!document.getElementById('card-container').textContent.includes('Available: 5'));
 check('Player may loot allowed item but not DM-only item',!!document.querySelector('[data-item-id="potion"] .loot-button')&&!document.querySelector('[data-item-id="dm-only"] .loot-button'));
 await click('#card-container [data-item-id="potion"] .loot-button');
 check('Loot character choices contain only own characters',document.querySelectorAll('#actionCharacter option').length===1&&document.querySelector('#actionCharacter option').value==='c1');
 document.getElementById('actionQuantity').value='2';await click('#confirmInventoryAction');
 check('Player loot submits selected character and quantity',callLog.at(-1).data.characterId==='c1'&&callLog.at(-1).data.quantity===2&&callLog.at(-1).data.action==='claim');
 check('Private player inventory refreshes with new quantity',document.querySelector('#myLootGrid .inventory-quantity').textContent==='Owned: 4');
 check('Player has Use but cannot unloot or transfer',!!document.querySelector('#myLootGrid .use-button')&&!document.querySelector('#myLootGrid .unloot-button')&&!document.querySelector('#myLootGrid .transfer-button'));
 await click('#card-container [data-item-id="potion"] .loot-button');testFailWrite=true;await click('#confirmInventoryAction');
 check('Failed loot keeps dialog open with error',document.getElementById('vaultActionDialog').open&&document.getElementById('actionError').textContent.includes('denied'));testFailWrite=false;closeVaultAction();
 await click('#card-container [data-item-id="potion"] .save-item-button');
 check('Player save write stays scoped to campaign and own character',testWrites.some(w=>w.path==='campaigns/a/saves/c1__potion'&&w.data.userId==='player'));
 seed('admin','player');
 check('Admin membership as player does not grant DM capabilities',!canManageCampaign()&&document.getElementById('dmTab').style.display==='none'&&!document.querySelector('#card-container .edit-button'));
 await openRootCatalogue();
 check('Admin root screen offers root editing only',document.getElementById('rootCatalogueScreen').style.display==='block'&&document.querySelector('#rootCards .edit-button').textContent==='Edit Root Item'&&!document.querySelector('#rootCards .assign-button'));
 await click('#rootCards .edit-button');check('Root editor has no campaign supply controls',!document.getElementById('modal-remaining'));
 document.getElementById('modal-name').value='Root Change';await click('#saveItemModal');
 check('Root edits write only to global items collection',testWrites.at(-1).path==='items/root-potion'&&testWrites.at(-1).data.name==='Root Change');
 check('Root edits leave campaign copy unchanged',items.find(i=>i.id==='potion').name==='Healing Potion');
 seed('dm');activeCampaign.inventoryVersion=1;renderCampaignToolbar();check('Legacy campaign has explicit upgrade control',!!document.getElementById('migrateCampaignInventory'));
 seed('player');activeCampaign.inventoryVersion=1;renderCampaignToolbar();check('Players cannot trigger migration',!document.getElementById('migrateCampaignInventory')&&document.getElementById('campaignInventoryToolbar').textContent.includes('DM'));
 seed('player');await testAuthCallback(null);check('Logout clears inventory and closes private views',inventory.length===0&&rootItems.length===0&&!document.getElementById('vaultActionDialog').open);
 }catch(error){results.push({name:error.stack,pass:false});}
 const pre=document.createElement('pre');pre.id='test-results';pre.textContent=JSON.stringify(results,null,2);document.body.prepend(pre);
})();
