const {test}=require('node:test'),assert=require('node:assert/strict');
const {createCampaignWorkspaceStore}=require('../js/modules/campaign-workspace-store');
function fixture(){const records={},writes=[];const snapshot=p=>({exists:()=>!!records[p],data:()=>records[p]});const store=createCampaignWorkspaceStore({db:{},auth:{currentUser:{uid:'dm'}},doc:(_, ...p)=>p.join('/'),collection:(_, ...p)=>p.join('/'),getDoc:async p=>snapshot(p),getDocs:async p=>({docs:Object.entries(records).filter(([key])=>key.startsWith(p+'/')).map(([key,data])=>({id:key.split('/').at(-1),data:()=>data}))}),runTransaction:async(_,fn)=>{const pending=[];const result=await fn({get:async p=>snapshot(p),set:(p,d)=>pending.push([p,d])});for(const [p,d]of pending){records[p]=structuredClone(d);writes.push(p)}return result;}});return{store,records,writes};}
const args={campaignId:'a',kind:'world',id:'north',revision:0,input:{title:'Northern Kingdom',content:'Snowy roads',privateNotes:'Cult below the tower',data:{category:'Region'}}};
test('world records save and reopen with secrets stored separately',async()=>{const {store,records}=fixture();const result=await store.save(args);assert.equal(result.revision,1);assert.equal(records['campaigns/a/worldEntries/north'].privateNotes,undefined);assert.equal(records['campaigns/a/workspaceSecrets/world-north'].notes,args.input.privateNotes);assert.equal((await store.load('a','world','north')).content,'Snowy roads');});
test('stale revisions never write over existing campaign data',async()=>{const {store,writes}=fixture();await store.save(args);const count=writes.length;await assert.rejects(store.save(args),/another window/);assert.equal(writes.length,count);});
test('archive and restore retain identity, authorship and other records',async()=>{const {store}=fixture();const first=await store.save(args);const next=await store.save({...args,revision:1,input:{...args.input,archived:true}});assert.equal(next.createdAt,first.createdAt);assert.equal(next.createdBy,'dm');assert.equal((await store.list('a','world')).length,1);assert.equal((await store.list('b','world')).length,0);});
test('invalid paths, oversized text and missing titles are rejected',async()=>{const {store}=fixture();for(const change of [{campaignId:'../b'},{id:'bad/path'},{kind:'members'},{input:{title:''}},{input:{title:'Valid',content:'x'.repeat(20001)}}])await assert.rejects(store.save({...args,...change}));});
test('linked records resolve only in the same campaign and never duplicate a master',async()=>{const {store,records}=fixture();await store.save({...args,kind:'creature',id:'valdris',input:{title:'Valdris'}});await store.save({...args,kind:'chapter',id:'two',input:{title:'Chapter 2',data:{links:[{kind:'creature',id:'valdris'}]}}});await store.save({...args,kind:'chapter',id:'three',input:{title:'Chapter 3',data:{links:[{kind:'creature',id:'valdris'}]}}});assert.equal((await store.list('a','creature')).length,1);await assert.rejects(store.save({...args,campaignId:'b',kind:'chapter',input:{title:'Other',data:{links:[{kind:'creature',id:'valdris'}]}}}),/linked record/);assert.equal(records['campaigns/b/chapters/north'],undefined);});
