// Real browser integration against a deterministic Firebase fixture; never touches production.
const fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_PATH || 'playwright');
(async()=>{
 const root=path.resolve(__dirname,'..'),browser=await chromium.launch({headless:true});
 try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',error=>{errors.push(error.message);console.error('Browser error:',error.message)});
 let html=fs.readFileSync(path.join(root,'index.html'),'utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<link\b[^>]*href="([^"]*)"[^>]*>/gi,(tag,href)=>href.startsWith('css/')?'<style>'+fs.readFileSync(path.join(root,href.split('?')[0]),'utf8')+'</style>':'');
 await page.route('https://fixture.example.test/**',route=>route.fulfill({contentType:'text/html',body:html}));await page.goto('https://fixture.example.test/');
 await page.evaluate(data=>{window.__testCatalog=data;window.print=()=>{};window.fetch=async()=>({ok:true,json:async()=>window.__testCatalog});window.alert=()=>{};window.confirm=()=>true;window.prompt=()=> 'Old Bridge'},JSON.parse(fs.readFileSync(path.join(root,'data/rules/catalog.json'),'utf8')));
 for(const file of ['dom-setup.js','dom-fixture.js'])await page.addScriptTag({path:path.join(__dirname,file)});
 await page.evaluate(()=>{const deps=window.__DND_VAULT_DEPS__;deps.where=(field,op,value)=>({field,op,value});deps.query=(path,...filters)=>({path,filters});deps.getDocs=async query=>{const p=typeof query==='string'?query:query.path,filters=query.filters||[];return {docs:Object.entries(testSheetDocs).filter(([key,data])=>key.startsWith(p+'/')&&key.slice(p.length+1).indexOf('/')<0&&filters.every(f=>{const value=f.field.split('.').reduce((d,k)=>d?.[k],data);return f.op==='array-contains'?value?.includes(f.value):value===f.value})).map(([key,data])=>({id:key.split('/').at(-1),data:()=>structuredClone(data)}))}};deps.ref=(_,p)=>p;deps.uploadBytes=async(p)=>{window.lastUpload=p};deps.getBlob=async()=>new Blob([Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aWQAAAABJRU5ErkJggg=='),c=>c.charCodeAt(0))],{type:'image/png'})});
 await page.addScriptTag({content:'function createCampaignStore(){return window.__DND_VAULT_DEPS__.vaultCall}'});
 const modules=fs.readFileSync(path.join(__dirname,'dom.cjs'),'utf8').match(/for\(const name of (\[[^\n]+?\])\)await run/)[1];
 for(const name of JSON.parse(modules.replaceAll("'",'"')))await page.addScriptTag({path:path.join(root,'js/modules',name+'.js')});
 await page.evaluate(()=>CharacterCatalog.set(window.__testCatalog));await page.addScriptTag({path:path.join(__dirname,'dom-state.js')});
 await page.evaluate(monsters=>{window.__testMonsters=monsters;window.fetch=async url=>({ok:true,json:async()=>String(url).includes('monsters.json')?window.__testMonsters:window.__testCatalog})},JSON.parse(fs.readFileSync(path.join(root,'data/rules/monsters.json'),'utf8')));
 await page.evaluate(()=>{seed('dm');showMainApp();showTab('dm-world')});
 await page.waitForSelector('[data-new-record]');await page.waitForFunction(()=>CampaignWorkspace.session?.rows);
 await page.locator('[data-new-record]').click();await page.locator('[name="title"]').fill('The Northern Kingdom');await page.locator('[name="content"]').fill('A snowy land');await page.locator('[name="privateNotes"]').fill('The king is an impostor');await page.locator('[data-save-record]').click();await page.waitForFunction(()=>CampaignWorkspace.session?.record?.revision===1);
 await page.locator('[name="content"]').fill('A cold and snowy land');await page.evaluate(()=>window.confirm=()=>false);await page.locator('[data-workspace-kind="creature"]').click();if(await page.locator('[name="title"]').inputValue()!=='The Northern Kingdom')throw Error('Unsaved navigation discarded draft');await page.evaluate(()=>window.confirm=()=>true);if(await page.locator('[name="title"]').inputValue()!=='The Northern Kingdom')throw Error('Editor closed during typing');await page.locator('[data-save-record]').click();await page.waitForFunction(()=>CampaignWorkspace.session?.record?.revision===2);
 await page.locator('[data-open-record]').click();await page.waitForFunction(()=>!CampaignWorkspace.session?.dirty);if(await page.locator('[name="privateNotes"]').inputValue()!=='The king is an impostor')throw Error('Secrets not restored');
 await page.locator('[data-preview-record]').click();if((await page.locator('[data-player-preview]').textContent()).includes('impostor'))throw Error('Secret leaked in preview');
 await page.locator('[data-map-upload]').setInputFiles({name:'map.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aWQAAAABJRU5ErkJggg==','base64')});await page.waitForFunction(()=>!!CampaignWorkspace.session?.record?.data?.imagePath);await page.locator('[data-save-record]').click();await page.waitForFunction(()=>CampaignWorkspace.session?.record?.revision===3);
 await page.waitForSelector('[data-map] img');await page.locator('[data-map] img').click({position:{x:20,y:20}});await page.locator('[data-save-record]').click();await page.waitForFunction(()=>CampaignWorkspace.session?.record?.revision===4);await page.locator('[data-open-record]').click();await page.waitForFunction(()=>!CampaignWorkspace.session?.dirty);if(await page.evaluate(()=>CampaignWorkspace.session.record.data.markers[0]?.label)!=='Old Bridge')throw Error('Map marker not persisted');await page.locator('[data-print-record]').click();if((await page.locator('#workspacePrintSurface').textContent()).includes('impostor'))throw Error('Print leaked private notes');await page.evaluate(()=>dispatchEvent(new Event('afterprint')));
 await page.screenshot({path:'/tmp/world80-desktop.png'});await page.setViewportSize({width:390,height:850});await page.screenshot({path:'/tmp/world80-mobile.png'});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');
 await page.setViewportSize({width:1440,height:1000});await page.locator('[data-workspace-kind="creature"]').click();await page.waitForSelector('[data-new-record]');await page.locator('[data-new-record]').click();await page.locator('[name="title"]').fill('Skeletal Knight');await page.locator('[data-record-field="category"]').selectOption('Monster');await page.locator('[data-record-field="hp"]').fill('45');await page.locator('[data-record-field="ac"]').fill('16');await page.locator('[data-record-field="actions"]').fill('Longsword: +5 to hit; 1d8 + 3 slashing damage.');await page.locator('[data-save-record]').click();await page.waitForFunction(()=>CampaignWorkspace.session?.record?.revision===1);if(!(await page.locator('[data-extra-editor]').textContent()).includes('45'))throw Error('Creature card not updated');await page.locator('[data-open-record]').click();await page.waitForFunction(()=>!CampaignWorkspace.session?.dirty);if(await page.locator('[data-record-field="hp"]').inputValue()!=='45')throw Error('Creature HP not persisted');
 console.log('PASS Shared monster card save/reopen and live preview');
 await page.locator('#dmPlanningTab-chapters').click();await page.waitForSelector('[data-new-record]');await page.locator('[data-new-record]').click();await page.locator('[name="title"]').fill('The Road North');await page.locator('[data-record-field="targetLevel"]').fill('8');await page.locator('[data-record-field="status"]').selectOption('Completed');
 await page.waitForFunction(()=>document.querySelector('[data-link-picker]')?.options.length>2);const creatureLink=await page.locator('[data-link-picker] option').evaluateAll(options=>options.find(o=>o.textContent.includes('Skeletal Knight'))?.value);await page.locator('[data-link-picker]').selectOption(creatureLink);await page.locator('[data-add-link]').click();await page.locator('[data-save-record]').click();await page.waitForFunction(()=>CampaignWorkspace.session?.record?.revision===1);
 if(await page.evaluate(()=>characters.find(c=>c.id==='c1').level)!==7)throw Error('Completing chapter changed character level');await page.locator('[data-approve-milestone="c1"]').click();await page.waitForFunction(()=>CampaignWorkspace.session?.record?.revision===2);if(await page.evaluate(()=>characters.find(c=>c.id==='c1').level)!==7)throw Error('Approval silently changed character level');
 console.log('PASS Chapter links, progress and explicit milestone approval without automatic level changes');
 await page.locator('[data-workspace-kind="encounter"]').click();await page.waitForSelector('[data-new-record]');await page.locator('[data-new-record]').click();await page.locator('[name="title"]').fill('Bridge Ambush');await page.waitForFunction(()=>document.querySelector('[data-combat-template]')?.options.length>1);await page.locator('[data-combat-template]').selectOption({label:'Skeletal Knight'});await page.locator('[data-combat-count]').fill('6');await page.locator('[data-add-combatant]').click();await page.waitForSelector('[data-damage-id]');await page.locator('[data-hp-amount]').first().fill('5');await page.locator('[data-damage-id]').first().click();await page.locator('[data-save-record]').click();await page.waitForFunction(()=>CampaignWorkspace.session?.record?.revision===1);
 const combat=await page.evaluate(()=>CampaignWorkspace.session.record.data.combatants);if(combat.filter(row=>row.hp===40).length!==1||combat.filter(row=>row.hp===45).length!==5)throw Error('Combat instances share HP');const masterHp=await page.evaluate(()=>Object.entries(testSheetDocs).find(([key,data])=>key.includes('/creatures/')&&data.title==='Skeletal Knight')[1].data.hp);if(masterHp!==45)throw Error('Encounter modified master');await page.locator('[data-next-turn]').click();await page.locator('[data-save-record]').click();await page.waitForFunction(()=>CampaignWorkspace.session?.record?.revision===2);
 console.log('PASS Six independent encounter combatants, damage, rounds and save without master changes');
 await page.locator('[data-workspace-kind="creature"]').click();await page.waitForSelector('[data-new-record]');await page.locator('[data-new-record]').click();await page.evaluate(()=>activeCampaign.allowedEditions=['2014']);await page.locator('[data-creature-catalog]').click();await page.waitForSelector('[data-import-monster]');if(await page.locator('[data-catalog-edition] option[value="2024"]').count())throw Error('Disallowed edition appears in catalogue');await page.locator('[data-catalog-search]').fill('Goblin');await page.locator('[data-catalog-edition]').selectOption('2014');await page.locator('[data-import-monster="srd-2014-goblin"]').click();if(await page.locator('[data-record-field="hp"]').inputValue()!=='7')throw Error('SRD HP import incorrect');if(!(await page.locator('[data-extra-editor]').textContent()).includes('CC BY 4.0'))throw Error('Attribution missing');await page.locator('[data-save-record]').click();await page.waitForFunction(()=>CampaignWorkspace.session?.record?.revision===1);if(await page.evaluate(()=>__testMonsters.records.find(row=>row.id==='srd-2014-goblin').data.hp)!==7)throw Error('Global source changed');
 console.log('PASS Local SRD catalogue search, edition selection, source attribution and campaign copy');
 await page.locator('#dmPlanningTab-one-shots').click();await page.waitForSelector('[data-new-record]');await page.locator('[data-new-record]').click();await page.locator('[name="title"]').fill('Rescue at Dusk');await page.locator('[data-record-field="targetLevel"]').fill('3');await page.locator('[name="privateNotes"]').fill('The mayor is the villain');await page.locator('[data-save-record]').click();await page.waitForFunction(()=>CampaignWorkspace.session?.record?.revision===1);await page.evaluate(()=>CampaignWorkspace.renderEditor());await page.waitForSelector('[data-shot-host]');await page.locator('[data-shot-host]').selectOption('player');await page.locator('[data-approve-shot]').click();await page.waitForFunction(()=>CampaignWorkspace.session?.record?.revision===2);await page.waitForSelector('[data-shot-invite]');await page.locator('[data-shot-invite]').selectOption('other');await page.locator('[data-invite-shot]').click();await page.waitForFunction(()=>CampaignWorkspace.session?.record?.revision===3);await page.waitForSelector('[data-new-shot-character]');await page.locator('[data-new-shot-character]').click();await page.waitForSelector('[data-open-shot-sheet]');
 const shotId=await page.evaluate(()=>CampaignWorkspace.session.record.id);
 await page.waitForSelector('[data-copy-shot-encounter]');await page.locator('[data-copy-shot-encounter]').selectOption({label:'Bridge Ambush'});await page.locator('[data-copy-encounter]').click();await page.waitForFunction(()=>!CampaignWorkspace.session.busy&&Object.keys(testSheetDocs).some(key=>key.includes('/oneShots/')&&key.includes('/encounters/')));
 await page.evaluate(()=>{CampaignWorkspace.clear(true);showTab('dm-one-shots')});await page.waitForSelector('[data-open-record]');await page.locator('[data-open-record]').click();await page.waitForSelector('[data-shot-encounters]');await page.locator('[data-shot-encounters]').click();await page.waitForSelector('[data-open-record]');await page.locator('[data-open-record]').click();await page.waitForSelector('[data-damage-id]');await page.locator('[data-hp-amount]').first().fill('3');await page.locator('[data-damage-id]').first().click();await page.locator('[data-save-record]').click();await page.waitForFunction(()=>CampaignWorkspace.session?.record?.revision===2);
 await page.locator('details summary').filter({hasText:'Add a homebrew opponent'}).click();await page.locator('[data-custom-name]').fill('Host-created bandit');await page.locator('[data-custom-hp]').fill('11');await page.locator('[data-add-custom-combatant]').click();await page.locator('[data-save-record]').click();await page.waitForFunction(()=>CampaignWorkspace.session?.record?.revision===3);
 const scopedCombat=await page.evaluate(()=>({copy:CampaignWorkspace.session.record.data.combatants.map(row=>row.hp),master:Object.entries(testSheetDocs).find(([key,data])=>key.startsWith('campaigns/a/encounters/')&&data.title==='Bridge Ambush')[1].data.combatants.map(row=>row.hp)}));if(scopedCombat.copy.join(',')===scopedCombat.master.join(','))throw Error('Adventure combat did not change independently');await page.locator('[data-print-private]').check();await page.locator('[data-print-record]').click();if(!(await page.locator('#workspacePrintSurface').textContent()).includes('Skeletal Knight'))throw Error('Run sheet lacks combatants');await page.emulateMedia({media:'print'});if(await page.locator('#mainApp').isVisible())throw Error('App chrome appears in printed run sheet');await page.pdf({path:'/tmp/workspace80-encounter.pdf',format:'A4',printBackground:true});await page.emulateMedia({media:'screen'});await page.evaluate(()=>dispatchEvent(new Event('afterprint')));
 console.log('PASS Campaign DM runs and prints private encounter copies without changing campaign combat');

 await page.evaluate(()=>{CampaignWorkspace.clear(true);showTab('dm-one-shots')});await page.waitForSelector('[data-open-record]');await page.locator('[data-open-record]').click();await page.waitForSelector('[data-open-shot-sheet]');await page.locator('[data-open-shot-sheet]').click();await page.waitForSelector('#characterSheetForm');await page.locator('[data-sheet-tab="builder"]').click();await page.locator('[name="identity.name"]').fill('One-shot Arden');await page.locator('#sheetSave').click();await page.waitForFunction(()=>sheetSession?.revision===1);
 const isolated=await page.evaluate(shotId=>({sheet:Object.keys(testSheetDocs).find(key=>key.includes('/oneShots/'+shotId+'/characterSheets/')),main:Object.keys(testSheetDocs).filter(key=>key.includes('/characters/')&&!key.includes('/oneShots/')),gear:sheetEquipmentLoot()}),shotId);if(!isolated.sheet||isolated.main.length||isolated.gear.length)throw Error('One-shot sheet or gear leaked into main campaign');
 await page.evaluate(()=>{closeCharacterSheet(true);CampaignWorkspace.clear(true);seed('player');renderDMTools();showTab('player')});
 for(const kind of ['world','chapters','one-shots']){if(await page.locator('#dmPlanningTab-'+kind).isVisible())throw Error('Player sees DM tab: '+kind);await page.evaluate(kind=>showTab('dm-'+kind),kind);if(await page.locator('#tab-dm-'+kind).isVisible())throw Error('Player opens DM tab directly: '+kind);}
 await page.evaluate(()=>CampaignWorkspace.render('oneShot'));if(await page.locator('#tab-dm-one-shots .campaign-workspace').count())throw Error('Player rendered DM editor');
 console.log('PASS DM adventure sheets remain isolated; players cannot see or navigate to any planning tab');
 if(errors.length)throw Error(errors.join('\n'));
 console.log('PASS World editor creation, reopen, private preview, persistent editor, image upload and mobile layout');
 }finally{await browser.close()}
})().catch(error=>{console.error(error);process.exitCode=1});
