#!/usr/bin/env python3
"""Extract static lists from user-supplied PDF JS streams, without executing PDF code.
Usage: python scripts/build-adobe-data.py /path/to/extracted/pdf-reference
"""
import argparse,json,pathlib,re
p=argparse.ArgumentParser();p.add_argument('streams',type=pathlib.Path);p.add_argument('--backgrounds',type=pathlib.Path);a=p.parse_args();root=pathlib.Path(__file__).resolve().parents[1]
def block(text,start):
 pos=text.index(start)+len(start);pos=text.index('{',pos);depth=0;quoted=False;escape=False
 for i in range(pos,len(text)):
  c=text[i]
  if quoted:
   if escape:escape=False
   elif c=='\\':escape=True
   elif c=='"':quoted=False
  elif c=='"':quoted=True
  elif c=='{':depth+=1
  elif c=='}':
   depth-=1
   if depth==0:return text[pos:i+1]
 raise ValueError('Unterminated object')
def literal(s):
 s=re.sub(r'\bregExpSearch\s*:\s*/[^\n]+?,','',s)
 s=re.sub(r'(?m)^\s*//.*$','',s)
 s=re.sub(r'(?m)^(\s*)([a-zA-Z_$][\w$]*)\s*:',r'\1"\2":',s)
 s=re.sub(r'(?<=[\s:,\[])\.(\d)',r'0.\1',s)
 s=re.sub(r',\s*([}\]])',r'\1',s)
 try:return json.loads(s)
 except json.JSONDecodeError as e:
  raise ValueError(s[max(0,e.pos-80):e.pos+80]) from e
sources={}
for f in a.streams.glob('*.txt'):
 t=f.read_text()
 for name in ['Base_GearList','Base_PacksList','Base_BackgroundList']:
  if 'var '+name+' =' in t:sources[name]=literal(block(t,'var '+name+' ='))
gear=[]
for key,v in sources['Base_GearList'].items():
 gear.append({'id':'gear-'+re.sub('[^a-z0-9]+','-',key.lower()).strip('-'),'name':v['name'], 'unitName':v['name'],'quantity':v.get('amount') or 1,'weight':v.get('weight') or 0,'price':re.search(r'\[(.*?)\]',v.get('infoname','')).group(1) if '[' in v.get('infoname','') else '', 'edition':'2014','category':v.get('type','Adventuring gear')})
packs=[{'id':k,'name':v['name'],'edition':'2014','items':[{'name':x[0],'quantity':x[1] or 1,'weight':x[2] or 0} for x in v['items']]} for k,v in sources['Base_PacksList'].items()]
story={k:{'name':v['name'],**{out:[x[1] if isinstance(x,list) else x for x in v.get(field,[])] for out,field in [('personality','trait'),('ideals','ideal'),('bonds','bond'),('flaws','flaw')]}} for k,v in sources['Base_BackgroundList'].items()}
if a.backgrounds:
 for b in json.loads(a.backgrounds.read_text())['background']:
  if b.get('source') not in ['PHB','XPHB'] or not b.get('startingEquipment'):continue
  edition='2024' if b['source']=='XPHB' else '2014';items=[]
  for group in b['startingEquipment']:
   for x in group.get('_',group.get('A',[])):
    if isinstance(x,str):items.append({'name':x.split('|')[0].title(),'quantity':1,'weight':0});continue
    if 'item' in x:items.append({'name':x['item'].split('|')[0].title(),'quantity':x.get('quantity',1),'weight':0})
    elif 'special' in x:items.append({'name':x['special'],'quantity':x.get('quantity',1),'weight':0,'choice':True})
    elif 'equipmentType' in x:items.append({'name':'Choose '+x['equipmentType'],'quantity':x.get('quantity',1),'weight':0,'choice':True})
    elif 'value' in x:items.append({'name':str(x['value']/100)+' GP (record coins separately)','quantity':1,'weight':0,'choice':True})
  if items:packs.append({'id':'background-'+re.sub('[^a-z0-9]+','-',b['name'].lower())+'-'+edition,'name':b['name']+' background gear (fixed items / option A)','edition':edition,'items':items})
# Read only factual equipment names/weights from static PDF list entries.
base_equipment=[]
for f in a.streams.glob('*.txt'):
 t=f.read_text()
 if 'var Base_ArmourList =' not in t or 'var Base_WeaponsList =' not in t:continue
 for section in ['Base_ArmourList','Base_WeaponsList']:
  part=block(t,'var '+section+' =')
  for entry in re.split(r'\n\t"[^"\n]+"\s*:\s*\{',part)[1:]:
   name=re.search(r'\n\t\tname\s*:\s*"([^"]+)"',entry)
   weight=re.search(r'\n\t\tweight\s*:\s*([0-9.]+)',entry)
   kind=re.search(r'\n\t\ttype\s*:\s*"([^"]+)"',entry)
   if section=='Base_WeaponsList' and (not kind or kind[1] not in ['Simple','Martial']):continue
   if name and weight:base_equipment.append({'id':'equipment-'+re.sub('[^a-z0-9]+','-',name[1].lower()),'name':name[1],'quantity':1,'weight':float(weight[1]),'edition':'2014','price':'','category':'Weapons & armor'})
# Shield weight and price: SRD 5.1 equipment table.
base_equipment.append({'id':'equipment-shield','name':'Shield','quantity':1,'weight':6,'edition':'2014','price':'10 gp','category':'Weapons & armor'})
out={'source':'User-supplied MorePurpleMoreBetter Adobe sheet; bundled SRD base lists','gear':gear,'baseEquipment':base_equipment,'packs':packs,'story':story}
(root/'data/rules/adobe-reference.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n')
(root/'js/modules/character-adobe-data.js').write_text('/* Generated by scripts/build-adobe-data.py. Static data only. */\nvar CharacterAdobeData = '+json.dumps(out,ensure_ascii=False,separators=(',',':'))+';\nif(typeof module!=="undefined"&&module.exports)module.exports=CharacterAdobeData;\n')
print(len(gear),'gear entries;',len(packs),'packs;',len(story),'background story tables')
