'use strict';
function setupCharacterPlayUI(){
 const f=sheetField,form=document.getElementById('characterSheetForm'),story=document.getElementById('sheet-story');
 const profile=document.createElement('div');profile.className='sheet-grid sheet-profile';
 profile.innerHTML=f('Gender','profile.gender','select',{values:[['','Choose'],['male','Male'],['female','Female'],['other','Other']]})+f('Age (years)','profile.age','number',{min:0})+f('Size','profile.size','select',{values:[['','Choose'],['small','Small'],['medium','Medium'],['large','Large']]})+f('Height (cm)','profile.height','number',{min:0})+f('Weight (kg)','profile.weight','number',{min:0})+['hair','eyes','skin'].map(k=>f(k==='skin'?'Skin color':k[0].toUpperCase()+k.slice(1),'profile.'+k)).join('');
 const alignment=form.querySelector('[name="alignment"]');alignment.closest('label').remove();
 profile.insertAdjacentHTML('beforeend',f('Alignment','alignment','select',{values:[['','Choose alignment'],...Object.keys(CharacterPlayRules.alignments).map(x=>[x,x]),...(sheetSession.data.alignment&&!Object.hasOwn(CharacterPlayRules.alignments,sheetSession.data.alignment)?[[sheetSession.data.alignment,sheetSession.data.alignment+' (saved)']]:[])]})+'<p id="sheetAlignmentHelp" class="sheet-help"></p>');
 story.querySelector('h3').after(profile);
 const preset=document.createElement('p');preset.id='sheetStoryPreset';preset.className='sheet-help';profile.after(preset);
 const columns=document.createElement('div');columns.className='sheet-story-columns';
 const left=document.createElement('div');left.className='sheet-story-left';
 const right=document.createElement('div');right.className='sheet-story-right';columns.append(left,right);preset.after(columns);
 left.append(profile);
 for(const key of ['appearance','allies','enemies'])left.append(form.querySelector(`[name="${key}"]`).closest('label'));
 right.append(preset);
 for(const key of ['personality','ideals','bonds','flaws']){
  const area=form.querySelector(`[name="${key}"]`),label=area.closest('label'),control=document.createElement('div');
  control.className='sheet-story-combobox';area.rows=1;area.readOnly=false;
  area.setAttribute('role','combobox');area.setAttribute('aria-autocomplete','none');area.setAttribute('aria-expanded','false');area.setAttribute('aria-haspopup','listbox');area.setAttribute('aria-controls','sheetStoryOptions-'+key);
  const toggle=document.createElement('button');toggle.type='button';toggle.className='sheet-story-toggle';toggle.dataset.storyToggle=key;toggle.textContent='▾';toggle.setAttribute('aria-label','Choose '+key+' suggestion');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-controls','sheetStoryOptions-'+key);
  const options=document.createElement('div');options.id='sheetStoryOptions-'+key;options.className='sheet-story-options';options.dataset.storyChoice=key;options.setAttribute('role','listbox');options.setAttribute('aria-label',key+' suggestions');options.hidden=true;
  area.before(control);control.append(area,toggle,options);right.append(label);
  const close=()=>{options.hidden=true;area.setAttribute('aria-expanded','false');toggle.setAttribute('aria-expanded','false');};
  const open=()=>{story.querySelectorAll('.sheet-story-options').forEach(list=>{if(list!==options){list.hidden=true;list.closest('.sheet-story-combobox').querySelectorAll('[aria-expanded]').forEach(el=>el.setAttribute('aria-expanded','false'));}});options.hidden=false;area.setAttribute('aria-expanded','true');toggle.setAttribute('aria-expanded','true');(options.querySelector('[aria-selected="true"]')||options.querySelector('button'))?.focus();};
  toggle.onclick=()=>options.hidden?open():close();
  area.addEventListener('keydown',event=>{if(event.altKey&&event.key==='ArrowDown'){event.preventDefault();open();}if(event.key==='Escape'){close();}});
  control.addEventListener('focusout',event=>{if(event.relatedTarget&&!control.contains(event.relatedTarget))close();});
  options.addEventListener('keydown',event=>{const buttons=[...options.querySelectorAll('button')],index=buttons.indexOf(document.activeElement);if(event.key==='Escape'){event.preventDefault();close();toggle.focus();}else if(['ArrowDown','ArrowUp','Home','End'].includes(event.key)){event.preventDefault();buttons[event.key==='Home'?0:event.key==='End'?buttons.length-1:(index+(event.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length]?.focus();}});
 }
 story.addEventListener('click',event=>{story.querySelectorAll('.sheet-story-combobox').forEach(control=>{if(!control.contains(event.target)){control.querySelector('.sheet-story-options').hidden=true;control.querySelectorAll('[aria-expanded]').forEach(el=>el.setAttribute('aria-expanded','false'));}});});
 const remaining=form.querySelector('[name="backstory"]').closest('.sheet-grid');remaining.classList.add('sheet-story-notes');
 updateStorySuggestions();
 const scoreMode=form.querySelector('[name="build.scoreMode"]')?.closest('label');if(scoreMode)document.querySelector('.sheet-point-panel').appendChild(scoreMode);
 const advancement=document.createElement('section');advancement.className='sheet-editor-box';advancement.innerHTML='<h4>Advancement</h4>'+f('ASI choices spent on ability scores instead of feats','advancement.asiSpent','number',{min:0,max:7})+'<p class="sheet-help">For 2014 ASIs already entered in your base scores, reserve their choices here. Do not also select an Ability Score Improvement feat for the same increase. Progression uses the class levels assigned in the Character Builder; multiclass levels are calculated separately for HP, hit dice, subclasses and spellcasting.</p>'+f('Warlock: one invocation spent on Lessons of the First Ones','advancement.lessons','checkbox')+'<p class="sheet-help">2024 Warlock, level 2+: reserves one invocation for an Origin feat. This does not grant an extra general feat.</p>';
 document.getElementById('sheetBuildControls').appendChild(advancement);
 const spells=document.getElementById('sheet-spells'),sheet=document.createElement('section');sheet.id='sheetSpellReadout';spells.querySelector('h3').after(sheet);
 const slots=spells.querySelector('.sheet-slot-grid');const slotDetails=document.createElement('details');slotDetails.className='sheet-spell-editor';slotDetails.innerHTML='<summary>Configure spell slot totals</summary>';slots.before(slotDetails);slotDetails.appendChild(slots);
 const rows=document.getElementById('sheetSpellRows'),edit=document.createElement('details');edit.id='sheetSpellEditor';edit.className='sheet-spell-editor';edit.innerHTML='<summary>Edit spell details / custom spells</summary>';rows.before(edit);edit.append(rows,document.getElementById('sheetAddSpell'));
 const gear=document.createElement('section');gear.id='sheetGearPicker';gear.className='sheet-editor-box';document.getElementById('sheetInventory').before(gear);renderSheetGearPicker();
}
function updateCharacterPlayUI(d){
 updateStorySuggestions();
 const s=sheetSession,help=document.getElementById('sheetAlignmentHelp');if(help)help.textContent=CharacterPlayRules.alignments[s.data.alignment]||'';
 const host=document.getElementById('sheetSpellReadout');if(!host)return;
 const esc=sheetEscape;
 const rows=s.data.spells.map((spell,i)=>({spell,i})).sort((a,b)=>a.spell.level-b.spell.level||a.spell.name.localeCompare(b.spell.name));
 host.innerHTML=`<div class="sheet-spell-heading"><div><small>Spellcasting ability</small><strong>${esc(CharacterSheetModel.abilities[s.data.spellAbility])}</strong></div><div><small>Save DC</small><strong>${d.spellDC}</strong></div><div><small>Attack modifier</small><strong>${CharacterSheetModel.signed(d.spellAttack)}</strong></div></div><div class="sheet-slot-trackers">${s.data.slots.map((slot,i)=>`<div><strong>${i+1}</strong><span>${slot.max-slot.used}/${slot.max}</span><div>${Array.from({length:slot.max},(_,j)=>`<button type="button" class="sheet-slot-orb" data-slot-level="${i}" data-slot-number="${j}" aria-label="Level ${i+1} slot ${j+1}, ${j<slot.used?'used':'available'}" aria-pressed="${j<slot.used}"></button>`).join('')||'—'}</div></div>`).join('')}</div><p class="sheet-help">Filled circles are used slots. Click to spend or restore slots; totals are configured below.</p><div class="sheet-spell-table-wrap"><table class="sheet-spell-table"><thead><tr>${['Prep','Lv','Spell','Short description','Save','School','Time','Range','Comp','Duration','B','P'].map(t=>`<th scope="col">${t}</th>`).join('')}</tr></thead><tbody>${rows.map(({spell:p,i})=>{const c=CharacterCatalog.find(p.catalogId),description=c?.shortDescription||c?.description||p.notes||'Source reference only';return `<tr><td><button type="button" data-prepare-spell="${i}" class="sheet-slot-orb" aria-label="Prepare ${esc(p.name)}" aria-pressed="${p.prepared}"></button></td><td>${p.level||'C'}</td><td><strong>${esc(p.name)}</strong><small>${esc(c?.edition||'Custom')}</small><button type="button" class="sheet-info-button" data-sheet-spell-info="${i}" aria-label="Information about ${esc(p.name)}">i</button></td><td>${esc(description.replace(/\s+/g,' ').slice(0,180))}${description.length>180?'…':''}</td><td>${esc(c?.save||'—')}</td><td>${esc(c?.school||'—')}</td><td>${esc(p.casting)}</td><td>${esc(p.range)}</td><td>${esc(p.components)}</td><td>${esc(p.duration)}</td><td title="${esc(c?.book||'')}">${esc(c?.source||'—')}</td><td>${c?.page?esc(c.page):'—'}</td></tr>`;}).join('')||'<tr><td colspan="12">Choose spells from the catalogue below.</td></tr>'}</tbody></table></div>`;
 host.querySelectorAll('[data-sheet-spell-info]').forEach(b=>b.onclick=()=>openSpellInformation({index:Number(b.dataset.sheetSpellInfo)}));
 host.querySelectorAll('[data-prepare-spell]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.prepareSpell);readSheetForm();s.data.spells[i].prepared=!s.data.spells[i].prepared;document.querySelector(`[name="spells.${i}.prepared"]`).checked=s.data.spells[i].prepared;catalogChanged('Prepared spells updated. Save to keep changes.');host.querySelector(`[data-prepare-spell="${i}"]`)?.focus();});
 host.querySelectorAll('[data-slot-level]').forEach(b=>b.onclick=()=>{readSheetForm();const i=Number(b.dataset.slotLevel),j=Number(b.dataset.slotNumber);s.data.slots[i].used=j<s.data.slots[i].used?j:j+1;document.querySelector(`[name="slots.${i}.used"]`).value=s.data.slots[i].used;catalogChanged('Spell slots updated. Save to keep changes.');host.querySelector(`[data-slot-level="${i}"][data-slot-number="${j}"]`)?.focus();});
 const budget=CharacterPlayRules.budget(s.data,s.identity.level,CharacterCatalog.data?.feats||[]),status=document.getElementById('sheetFeatBudget');
 if(status)status.textContent=`Available choices: ${budget.remaining} feat · ${budget.asiRemaining} ASI · ${budget.style} Fighting Style · ${budget.lessons} invocation Origin.${budget.bonusFeats||budget.bonusAsis?` DM approved: +${budget.bonusFeats} feat / +${budget.bonusAsis} ASI.`:''}${budget.over?' '+budget.over+' existing choices exceed the approved progression; review with your DM. Saved feats have been preserved.':''}`;
 const signature=JSON.stringify([s.identity.level,s.data.build.classId,s.data.build.race,s.data.build.edition,s.data.build.raceFeat,s.data.advancement,s.data.rulesChoices.feats,s.data.rulesChoices.grants?.__dm,d.scores]);
 if(host.dataset.featSignature!==signature){host.dataset.featSignature=signature;if(document.getElementById('catalogFeatResults'))renderCatalogFeatResults();}
}
